<?php
/**
 * storage.php
 *
 * Tiny flat-file storage layer. No database, no Composer, no external
 * dependencies -- just plain PHP file I/O so this runs on any shared
 * host that can execute PHP.
 *
 * Owns three kinds of data: data/config.php (settings), data/chats/
 * (one JSON file per conversation + one-shot error files) and
 * data/memories/ (the plain-text memory files, see lib/memory.php).
 */

define('DATA_DIR', __DIR__ . '/../data');
define('CONFIG_FILE', DATA_DIR . '/config.php');
define('CHATS_DIR', DATA_DIR . '/chats');

// Memory files (data/memories/) ride in with the storage layer: they
// are flat data files just like the chats, and every entry point
// needs them (chat retrieval, the memories.php manager page).
require_once __DIR__ . '/memory.php';

/**
 * Make sure the data directories exist. Called once at the top of
 * every entry point (setup.php, index.php).
 */
function storage_init() {
    if (!is_dir(DATA_DIR)) {
        @mkdir(DATA_DIR, 0700, true);
    }
    if (!is_dir(CHATS_DIR)) {
        @mkdir(CHATS_DIR, 0700, true);
    }
    // Also creates data/memories/ + its README.txt on first run, so
    // the folder is ready right after setup.php has been visited.
    memory_init();
}

/**
 * Has setup.php already been run?
 */
function config_exists() {
    return file_exists(CONFIG_FILE);
}

/**
 * Defaults merged into whatever is loaded from config.php, so a
 * hand-edited config missing a newer key (e.g. someone editing an old
 * install after an upgrade) doesn't produce undefined-index warnings.
 */
function config_defaults() {
    return array(
        // Optional: only sent to llama-server when non-empty. Harmless
        // with a plain single-model llama-server; useful when a router
        // in front of several models needs a model id.
        'model' => '',
        'llamacpp_endpoint' => LLAMACPP_DEFAULT_ENDPOINT,
        // Seconds to wait for a llama.cpp reply before giving up.
        // CPU-only inference is slow (a 300-token reply at ~7 tokens/s
        // needs ~45 s); raise this by hand for very slow boxes.
        'llamacpp_timeout' => 120,
        'companion_name' => 'Companion',
        'user_name' => 'Friend',
        // Optional persona note edited on settings.php; appended to the
        // system prompt by index.php when non-empty.
        'persona' => '',
        // Which themes/*.css file the UI uses. '' = browser default
        // (no stylesheet), the original skeleton look.
        'theme' => '',
    );
}

/**
 * Read the config file as an associative array, or null if missing/corrupt.
 * config.php is a plain PHP file that `return`s an array -- readable
 * and hand-editable, and unlike a .json file it executes rather than
 * leaks its contents even if .htaccess protection ever fails.
 */
function get_config() {
    if (!config_exists()) {
        return null;
    }
    $data = @include CONFIG_FILE;
    if (!is_array($data)) {
        return null;
    }
    return array_merge(config_defaults(), $data);
}

/**
 * Overwrite the config file with the given associative array.
 * Returns true on success. Called by setup.php (first run, full form)
 * and by settings.php (personal settings) -- settings.php passes the
 * FULL current config with its keys replaced, so backend/API-key
 * settings survive a personal-settings save. After setup.php has run,
 * everything NOT on settings.php is changed by hand-editing
 * config.php.
 */
function save_config($data) {
    storage_init();
    $data = array_merge(config_defaults(), $data);
    $php = "<?php\n"
        . "// Generated by setup.php. Safe to hand-edit afterwards --\n"
        . "// setup.php will not overwrite this file once it exists.\n"
        . "return " . var_export($data, true) . ";\n";
    // LOCK_EX: two overlapping requests must not corrupt the file.
    $ok = @file_put_contents(CONFIG_FILE, $php, LOCK_EX);
    return $ok !== false;
}

/**
 * Load a chat history (array of ["role" => ..., "content" => ...]) for
 * the given session id. Returns an empty array if none exists yet.
 */
function load_chat($session_id) {
    $path = session_path($session_id, '.json');
    if (!file_exists($path)) {
        return array();
    }
    $raw = @file_get_contents($path);
    $data = json_decode($raw, true);
    return is_array($data) ? $data : array();
}

/**
 * Save a chat history array for the given session id.
 */
function save_chat($session_id, $messages) {
    storage_init();
    $path = session_path($session_id, '.json');
    $json = json_encode($messages, JSON_UNESCAPED_SLASHES);
    if ($json === false) {
        return false;
    }
    // LOCK_EX: two overlapping requests must not corrupt the file.
    return @file_put_contents($path, $json, LOCK_EX) !== false;
}

/**
 * Build a safe file path for a given session id, so a crafted session
 * id can never be used for path traversal.
 */
function session_path($session_id, $ext) {
    $safe_id = preg_replace('/[^a-zA-Z0-9_-]/', '', (string) $session_id);
    if ($safe_id === '') {
        $safe_id = 'default';
    }
    return CHATS_DIR . '/' . $safe_id . $ext;
}

function chat_path($session_id) {
    return session_path($session_id, '.json');
}

/**
 * One-shot "flash" error store. The POST handler redirects (so a page
 * reload doesn't resend the message), which would otherwise swallow
 * the API error before it is ever rendered. The error survives in a
 * sidecar file and is shown once on the next page load. Passed as a
 * URL parameter instead would risk tripping URL length limits on the
 * old browsers this app targets.
 */
function save_error($session_id, $error) {
    storage_init();
    @file_put_contents(session_path($session_id, '.err'), (string) $error, LOCK_EX);
}

function pop_error($session_id) {
    $path = session_path($session_id, '.err');
    if (!file_exists($path)) {
        return '';
    }
    $error = (string) @file_get_contents($path);
    @unlink($path);
    return $error;
}
